apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "dev-ap"
  spec:
    source:
      type: "Git"
      git:
        uri: "ssh://git@bitbucketglobal.experian.local/cah/instaclustr-sampleclient.git"
      sourceSecret:
        name: "sshsecret"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
kind: List
metadata: []